FROM python:3.5-slim

MAINTAINER HaiQuan "haiquan5396@gmail.com"

ENV TIME_PUSH_CONFIG 15
ENV TIME_PUSH_STATE 2

COPY Fog/Driver/HomeAssistant/requirements.txt /app/requirements.txt

VOLUME /app/config

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY Fog/Driver/HomeAssistant/HomeAssistant_Driver.py /app
COPY Semantic_Analysis /app/Semantic_Analysis
COPY Fog/Driver/Driver_Base.py /app/Fog/Driver/Driver_Base.py

CMD python3 HomeAssistant_Driver.py ${TIME_PUSH_CONFIG} ${TIME_PUSH_STATE}

#docker build -t haiquan5396/homeassistant_driver:1.3 -f Dockerfile_Home_Assistant .
#docker run -it --name home-driver-test -v /config: /app/config haiquan5396/homeassistant_driver:1.0
